# Generated by Django 5.1.4 on 2025-01-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_userprofile_photo_url_userprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
